/****************************************************

	JConfig Source Code Distribution
	version: 2.2.0      written: 08/23/2002 12:25 PM PDT

	Unless otherwise noted, all contents
	Copyright (c) 1997-2002 Samizdat Productions.
	All Rights Reserved.
	All contents are subject to the terms of the
	JConfig Source Code License Agreement

****************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jconfig_mac_AppFinderMRJ */

#ifndef _Included_com_jconfig_mac_AppFinderMRJ
#define _Included_com_jconfig_mac_AppFinderMRJ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jconfig_mac_AppFinderMRJ
 * Method:    nFindAPPLSingle
 * Signature: (I[I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppFinderMRJ_nFindAPPLSingle
  (JNIEnv *, jclass, jint, jintArray, jbyteArray, jint);

/*
 * Class:     com_jconfig_mac_AppFinderMRJ
 * Method:    nFindAPPLMultiple
 * Signature: (I[I[I[BII[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppFinderMRJ_nFindAPPLMultiple
  (JNIEnv *, jclass, jint, jintArray, jintArray, jbyteArray, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
