/****************************************************

	JConfig Source Code Distribution
	version: 2.2.0      written: 08/23/2002 12:25 PM PDT

	Unless otherwise noted, all contents
	Copyright (c) 1997-2002 Samizdat Productions.
	All Rights Reserved.
	All contents are subject to the terms of the
	JConfig Source Code License Agreement

****************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jconfig_mac_AppUtilsMRJ */

#ifndef _Included_com_jconfig_mac_AppUtilsMRJ
#define _Included_com_jconfig_mac_AppUtilsMRJ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetRawResourceFork
 * Signature: (III[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetRawResourceFork
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nSetRawResourceFork
 * Signature: (III[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nSetRawResourceFork
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nSetForkLength
 * Signature: (IIII[BJ)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nSetForkLength
  (JNIEnv *, jclass, jint, jint, jint, jint, jbyteArray, jlong);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nSendAppDocs
 * Signature: (I[I[Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nSendAppDocs
  (JNIEnv *, jclass, jint, jintArray, jobjectArray, jint);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nQuitApp
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nQuitApp
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nLaunchApp
 * Signature: (II[B[II)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nLaunchApp
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray, jint);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nLaunchWithDoc
 * Signature: (III[B[Ljava/lang/String;[II)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nLaunchWithDoc
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray, jobjectArray, jintArray, jint);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nCreateFullPathName
 * Signature: (II[B[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nCreateFullPathName
  (JNIEnv *, jclass, jint, jint, jbyteArray, jobjectArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetOpenableFileTypes
 * Signature: (II[I[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetOpenableFileTypes
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetFileDate
 * Signature: (III[B[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetFileDate
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nSetFileDate
 * Signature: (III[B[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nSetFileDate
  (JNIEnv *, jclass, jint, jint, jint, jbyteArray, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetVolumeDate
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetVolumeDate
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nSetVolumeDate
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nSetVolumeDate
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nVerifyPSN
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nVerifyPSN
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nMoveApp
 * Signature: ([III)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nMoveApp
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nLaunchURLDirect
 * Signature: (Ljava/lang/String;I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nLaunchURLDirect
  (JNIEnv *, jclass, jstring, jint, jobjectArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nFullPathToSpec
 * Signature: (Ljava/lang/String;[I[B)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nFullPathToSpec
  (JNIEnv *, jclass, jstring, jintArray, jbyteArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetFinderInfo
 * Signature: (II[B[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetFinderInfo
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nSetCreatorAndType
 * Signature: (II[B[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nSetCreatorAndType
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nVerifyFile
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nVerifyFile
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nVerifyVolume
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nVerifyVolume
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetDiskFileFlags
 * Signature: (II[B[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetDiskFileFlags
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nSetDiskFileFlags
 * Signature: (II[BII)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nSetDiskFileFlags
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetDFWriteFlagsMask
 * Signature: (II[B[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetDFWriteFlagsMask
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetDFReadFlagsMask
 * Signature: (II[B[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetDFReadFlagsMask
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetDiskVolumeFlags
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetDiskVolumeFlags
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nSetDiskVolumeFlags
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nSetDiskVolumeFlags
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetDVReadFlagsMask
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetDVReadFlagsMask
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetDVWriteFlagsMask
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetDVWriteFlagsMask
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetVolumes
 * Signature: (I[I[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetVolumes
  (JNIEnv *, jclass, jint, jintArray, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nUpdateContainer
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nUpdateContainer
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetFileCategory
 * Signature: (II[B[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetFileCategory
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetForkSizes
 * Signature: (II[B[J)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetForkSizes
  (JNIEnv *, jclass, jint, jint, jbyteArray, jlongArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nRenameFile
 * Signature: (II[B[BLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nRenameFile
  (JNIEnv *, jclass, jint, jint, jbyteArray, jbyteArray, jstring);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nRenameVolume
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nRenameVolume
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetVolumeCapacity
 * Signature: (I[J)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetVolumeCapacity
  (JNIEnv *, jclass, jint, jlongArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetVolumeFreeSpace
 * Signature: (I[J)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetVolumeFreeSpace
  (JNIEnv *, jclass, jint, jlongArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nCreateAlias
 * Signature: (II[BLjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nCreateAlias
  (JNIEnv *, jclass, jint, jint, jbyteArray, jstring, jint, jint);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetVolumeName
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetVolumeName
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nResolveAlias
 * Signature: (II[B[I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nResolveAlias
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray, jbyteArray, jint);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nSetColorCoding
 * Signature: (II[BI)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nSetColorCoding
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nSetVolumeColorCoding
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nSetVolumeColorCoding
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetVolumeFinderInfo
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetVolumeFinderInfo
  (JNIEnv *, jclass, jint, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetVolumeIconSuite
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetVolumeIconSuite
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetFileIconSuite
 * Signature: (II[BI[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetFileIconSuite
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetFTACIconSuite
 * Signature: (IIII[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetFTACIconSuite
  (JNIEnv *, jclass, jint, jint, jint, jint, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nPlotIcon
 * Signature: (IIIIII[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nPlotIcon
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nCreateVolumeAlias
 * Signature: (ILjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nCreateVolumeAlias
  (JNIEnv *, jclass, jint, jstring, jint, jint);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nIterateContents
 * Signature: (II[B[I[I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nIterateContents
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray, jintArray, jbyteArray, jint, jint);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nIVC
 * Signature: (I[I[I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nIVC
  (JNIEnv *, jclass, jint, jintArray, jintArray, jbyteArray, jint, jint);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetContainer
 * Signature: (II[B[I[B)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetContainer
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray, jbyteArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nDisposeIconSuite
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nDisposeIconSuite
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetAllMonitorInfo
 * Signature: ([II[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetAllMonitorInfo
  (JNIEnv *, jclass, jintArray, jint, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetMainMonitorInfo
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetMainMonitorInfo
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_jconfig_mac_AppUtilsMRJ
 * Method:    nGetProcesses
 * Signature: (II[I[I[I[B[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_AppUtilsMRJ_nGetProcesses
  (JNIEnv *, jclass, jint, jint, jintArray, jintArray, jintArray, jbyteArray, jintArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
