/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xct.cms.program.action;

import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xct.cms.dao.ProgramDAO;
import com.xct.cms.dao.TerminalDAO;
import com.xct.cms.domin.Terminal;
import com.xct.cms.domin.Users;
import com.xct.cms.servlet.FirstStartServlet;
import com.xct.cms.utils.PageDAO;
import com.xct.cms.utils.Pager;
import com.xct.cms.utils.Util;
import com.xct.cms.utils.UtilDAO;

/** 
 * MyEclipse Struts
 * Creation date: 08-28-2010
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class AddHtmlTextAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		    try {
				request.setCharacterEncoding("UTF-8");
			} catch (UnsupportedEncodingException e) {
				e.printStackTrace();
			}
		    String htmltextContenttmp=request.getParameter("htmltextContent");
		    String  isupscrolltext=request.getParameter("isupscrolltext");
		    
		    //System.out.println("htmltextContenttmp===>"+htmltextContenttmp);
		    
		    String htmltextbg=request.getParameter("htmltextbg");
		    String moduleid = request.getParameter("moduleid") == null ? "0": request.getParameter("moduleid");
	
		    UtilDAO utildao= new UtilDAO();
			Map map= utildao.getMap();
			map.put("id",moduleid);
			map.put("m_other","htmltext"+moduleid+".html");
			map.put("m_text",htmltextContenttmp);
			map.put("state","1");
			map.put("foreground",(null==isupscrolltext?"1":isupscrolltext));//暂定foreground 为判断是否为静态文本
			
			String filepath=FirstStartServlet.projectpath+"serverftp/module_file/htmltext"+moduleid+".html";
			Util.writefile(filepath,"<style>body{margin:0px;};</style><div  style='white-space:normal; word-break:break-all;background-color:#"+htmltextbg+"'>"+htmltextContenttmp+"</div>");
			utildao.updateinfo(map,"xct_module_temp");
			request.setAttribute("ophtmltext","save_ok");
			request.setAttribute("moduleid",request.getParameter("moduleid"));
			
		return mapping.findForward("toaddmedialist");
	}
}