/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xct.cms.program.action;
import com.xct.cms.dao.ProgramDAO;
import com.xct.cms.domin.Users;
import com.xct.cms.utils.Util;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.net.URLEncoder;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;


/** 
 * MyEclipse Struts
 * Creation date: 08-28-2010
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class ProgramDownloadFileAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String programe_file=request.getParameter("programe_file");//选择要下载的节目名称
		//String programefile[] = programe_file.split("!"); 
		String  mac_home=System.getProperty("MAC_HOME");
		
		String export_program=mac_home+"export_program";
		Util.createFile(export_program);
		
		String download_program=mac_home+"download_program\\";
		Util.createFile(download_program);
		
		ProgramDAO prodap= new ProgramDAO();
		String programname=prodap.getProgramByJmUrl(programe_file);

		//for(int i=0;i<programefile.length;i++){
//		 	if(!"".equals(programefile[i])){
//		 		Util.copyFolder(mac_home+programefile[i],machometmp+"\\"+programefile[i]);
//		 	}
		// }
		Util.copyFolder(mac_home+programe_file,export_program+"\\"+programe_file);
		try {
			programname=URLEncoder.encode(programname+".zip", "UTF-8");
			String zipfile=download_program+programname;
			Util.zip(zipfile,export_program);
			
			File[] file=new File(export_program).listFiles();
			for (File file2 : file) {
				Util.deleteFile(file2.getAbsolutePath());
			}
			
		    request.setAttribute("zipfile",programname);
		    
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		}
		//========================================================================

		return mapping.findForward("download4Autding");
	}
}