/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xct.cms.program.action;



import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xct.cms.dao.ProgramDAO;
import com.xct.cms.domin.Users;


/** 
 * MyEclipse Struts
 * Creation date: 08-28-2010
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class ProgramAuditingStatusAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String programe_file=request.getParameter("programe_file")==null?"":request.getParameter("programe_file");
		String op=request.getParameter("op")==null?"":request.getParameter("op");
		Users user = (Users) request.getSession().getAttribute("lg_user");
		if(null!=user){
			ProgramDAO programdao = new ProgramDAO();
			int backcode=0;
			
				if("update".equals(op)){
					if("1".equals(user.getLg_role())||"2".equals(user.getLg_role())){
					   backcode=programdao.updateProgramAuditingStatus(programe_file);
					}
				}else if("getstatus".equals(op)){
					//System.out.println("programe_file======================>"+programe_file);
					backcode=programdao.getProgramAuditingStatus(programe_file);
				}
			
			PrintWriter out;
			try {
				out = response.getWriter();
				out.print(backcode);
				out.flush();
				out.close();
			} catch (IOException e) {
				e.printStackTrace();
			}
			
		}
		
		return null;
	}
}