/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xct.cms.upload.action;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xct.cms.utils.UtilDAO;

import ahxu.commons.upload.DefaultReportItemManage;
import ahxu.commons.upload.ReportItem;

/**
 * MyEclipse Struts Creation date: 08-30-2010
 * 
 * XDoclet definition:
 * 
 * @struts.action scope="request" validate="true"
 */
public class ProgressdetailAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws IOException {
		// TODO Auto-generated method stub
		HttpSession ses;
		ReportItem aReportItem;
		PrintWriter writer = response.getWriter();
		ses = request.getSession(false);
		aReportItem = DefaultReportItemManage.getItem(ses);
		if (aReportItem != null) {
			writer.println("<detail-start>");
			String filename=aReportItem.getFileName();
			writer.println( filename+ "||"
					+ aReportItem.getCompletePercent() + "||"
					+ aReportItem.getUploadSpeedKB() + "||"
					+ aReportItem.getUploadSizeMKB() + "||"
					+ aReportItem.getTotalSizeMKB() + "||"
					+ aReportItem.getRemainTimeHMS() + "||"
					+ aReportItem.getTotalTimeHMS());
			writer.println("</detail-start>");
		}
		return null;
	}
}