/****************************************************

	JConfig Source Code Distribution
	version: 2.2.0      written: 08/23/2002 12:25 PM PDT

	Unless otherwise noted, all contents
	Copyright (c) 1997-2002 Samizdat Productions.
	All Rights Reserved.
	All contents are subject to the terms of the
	JConfig Source Code License Agreement

****************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jconfig_mac_XUtilsOSX */

#ifndef _Included_com_jconfig_mac_XUtilsOSX
#define _Included_com_jconfig_mac_XUtilsOSX
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jconfig_mac_XUtilsOSX
 * Method:    nGetPOSIXPath
 * Signature: (II[B[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_XUtilsOSX_nGetPOSIXPath
  (JNIEnv *, jclass, jint, jint, jbyteArray, jobjectArray );

/*
 * Class:     com_jconfig_mac_XUtilsOSX
 * Method:    nGetProcessBundleLocation
 * Signature: ([I[I[B)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_XUtilsOSX_nGetProcessBundleLocation
  (JNIEnv *, jclass, jintArray, jintArray, jbyteArray );

/*
 * Class:     com_jconfig_mac_XUtilsOSX
 * Method:    nFindApplicationForInfo
 * Signature: (ILjava/lang/String;Ljava/lang/String;[I[B)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_XUtilsOSX_nFindApplicationForInfo
  (JNIEnv *, jclass, jint, jstring, jstring, jintArray, jbyteArray );


/*
 * Class:     com_jconfig_mac_XUtilsOSX
 * Method:    nGetApplicationForInfo
 * Signature: (IILjava/lang/String;I[I[B)I
 */
JNIEXPORT jint JNICALL Java_com_jconfig_mac_XUtilsOSX_nGetApplicationForInfo
  (JNIEnv *, jclass, jint, jint, jstring, jint, jintArray, jbyteArray );

#ifdef __cplusplus
}
#endif
#endif

