/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xct.cms.media.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xct.cms.dao.MediaDAO;

/** 
 * MyEclipse Struts
 * Creation date: 08-29-2010
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class LeftmenuAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		String cmd=request.getParameter("cmd");
		if("MEDIA".equals(cmd)){
			////根据媒体类型查询各个媒体的数量
			MediaDAO mediadao= new MediaDAO();
			int movie=mediadao.getNumByMediaType("and media_type='MOVIE'");
			int image=mediadao.getNumByMediaType("and media_type='IMAGE'");
			int sound=mediadao.getNumByMediaType("and media_type='SOUND'");
			int office=mediadao.getNumByMediaType("and media_type='OFFICE'");
			int flash=mediadao.getNumByMediaType("and media_type='FLASH'");
			int ppt=mediadao.getNumByMediaType("and media_type='PPT'");
			int word=mediadao.getNumByMediaType("and media_type='WORD'");
			int excel=mediadao.getNumByMediaType("and media_type='EXCEL'");
			int text=mediadao.getNumByMediaType("and media_type='TEXT' and zu_name!='sys_text'");
			int web=mediadao.getNumByMediaType("and media_type='WEB'");
			int other=mediadao.getNumByMediaType("and media_type='OTHER'");
			request.setAttribute("movie", movie);
			request.setAttribute("image", image);
			request.setAttribute("sound", sound);
			request.setAttribute("office", office);
			request.setAttribute("flash", flash);
			request.setAttribute("ppt", ppt);
			request.setAttribute("word", word);
			request.setAttribute("excel", excel);
			request.setAttribute("text", text);
			request.setAttribute("web", web);
			request.setAttribute("other", other);
		}else if("CATEGORY".equals(cmd)){
			
		
		}else if("DATE".equals(cmd)){
			
		}
		
		return mapping.findForward(cmd);
	}
}