/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xct.cms.struts.action;

import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xct.cms.dao.TerminalDAO;
import com.xct.cms.domin.Terminal;
import com.xct.cms.form.AuditCntForm;
import com.xct.cms.servlet.FirstStartServlet;
import com.xct.cms.utils.UtilDAO;
 
/** 
 * MyEclipse Struts
 * Creation date: 08-23-2010
 * 
 * XDoclet definition:
 * @struts.action path="/auditCnt" name="auditCntForm" scope="request" validate="true"
 */
public class AuditCntAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AuditCntForm auditCntForm = (AuditCntForm) form;
		
		String cnt_name=auditCntForm.getCnt_name();
		String terminal_zu=auditCntForm.getTerminal_zu();
		String cnt_mac=auditCntForm.getTerminal_mac();
		String cnt_kjtime=auditCntForm.getCnt_kjtime();
		String cnt_gjtime=auditCntForm.getCnt_gjtime();
		String cnt_downtime=auditCntForm.getCnt_downtime();
		String cnt_miaoshu=auditCntForm.getCnt_miaoshu();
		UtilDAO utildao= new UtilDAO();
		Map map= utildao.getMap();
		map.put("cnt_mac", cnt_mac);
		map.put("cnt_name", cnt_name);
		map.put("cnt_kjtime", cnt_kjtime);
		map.put("cnt_gjtime", cnt_gjtime);
		map.put("cnt_downtime", cnt_downtime);
		map.put("cnt_miaoshu", cnt_miaoshu);
		map.put("cnt_zuid", terminal_zu);
		map.put("cnt_status", "1");
		utildao.updateinfo(map, "xct_ipaddress");
		//有出现异常：从数据类型 varchar 转换为 bigint 时出错
		Terminal tt=new TerminalDAO().getZuByUsername(" where zu_id='"+terminal_zu+"'");
		String zu_name=tt.getZu_name();
		
		Map<String,Terminal> terminalmaps=FirstStartServlet.terminalMap;
		Terminal terminal=terminalmaps.get(cnt_mac);
		terminal.setCnt_status("1");
		terminal.setCnt_zuid(Integer.parseInt(terminal_zu));
		terminal.setCnt_name(cnt_name);
		terminal.setCnt_kjtime(cnt_kjtime);
		terminal.setCnt_gjtime(cnt_gjtime);
		terminal.setCnt_downtime(cnt_downtime);
		terminal.setCnt_miaoshu(cnt_miaoshu);
		terminal.setZu_name(zu_name);
		FirstStartServlet.terminalMap.put(cnt_mac, terminal);
		
		FirstStartServlet.RESPONSE_INTERFACE_TERMINALMAP.put(cnt_mac, terminal);
		
		request.setAttribute("auditstatus", "1");
		return mapping.findForward("auditOk");
	}
}