/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xct.cms.action;

import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xct.cms.dao.TerminalDAO;
import com.xct.cms.domin.Terminal;
import com.xct.cms.domin.Users;

public class SearchTerminalAction extends Action {
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String cmd=request.getParameter("cmd");
		Users user = (Users) request.getSession().getAttribute("lg_user");
		TerminalDAO terminaldao= new TerminalDAO();
		if("AUDIT".equals(cmd)){
			Map<Integer,Terminal> map=TerminalDAO.getZuListByUsername(user.getLg_name());
			Terminal terminal = map.get(1);
			terminal.setZu_pth(-1);
			map.put(1, terminal);
			request.setAttribute("allterminal_zu", map);
			
		}else if("TERMINAL".equals(cmd)){
			Map<Integer,Terminal> map=TerminalDAO.getZuListByUsername(user.getLg_name());
			request.getSession().setAttribute("user_cnt_zu_map",map);
			Terminal terminal = map.get(1);
			terminal.setZu_pth(-1);
			map.put(1, terminal);
			request.setAttribute("allterminal_zu", map);
		}
		else if("MEDIA".equals(cmd)){
			String str=new StringBuffer().append("and (zu_username ='").append(user.getLg_name()).append("||' or is_share=1)").toString();
			if("1".equals(user.getLg_role())){
				str="";
			}
			List meida_zu=terminaldao.getAllZu(new StringBuffer().append(" where zu_type=1 ").append(str).append("  and zu_name <>'sys_text' order by is_share ").toString());
			request.setAttribute("meida_zu", meida_zu);
			
		}else if("NEWMEDIA_ZU".equals(cmd)){
			String str=new StringBuffer().append("and (zu_username ='").append(user.getLg_name()).append("||' or is_share=1)").toString();
			if("1".equals(user.getLg_role())){
				str="";
			}
			List meida_zu=terminaldao.getAllZu(new StringBuffer().append(" where zu_type=1 ").append(str).append(" and zu_name <>'sys_text' order by is_share ").toString());
			request.setAttribute("meida_zu", meida_zu);
		}
		return mapping.findForward(cmd);
	}
}