/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xct.cms.action;

import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xct.cms.dao.TerminalDAO;
import com.xct.cms.domin.Terminal;
import com.xct.cms.servlet.FirstStartServlet;

/** 
 * MyEclipse Struts
 * Creation date: 08-22-2010
 * 
 * XDoclet definition:
 * @struts.action scope="request" validate="true"
 */
public class ViweAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		 
		String terminal_mac=request.getParameter("cid")==null?"":request.getParameter("cid");
		String cmd=request.getParameter("cmd");
		TerminalDAO terminaldao= new TerminalDAO();
		
		boolean boolB=false;
		Terminal terminal=null;
		Map<String,Terminal> terminals=FirstStartServlet.terminalMap;
		if(null!=terminals&&terminals.size()>0){
			for (Map.Entry<String, Terminal> entry : terminals.entrySet()){
				Terminal  terminaltmp=(Terminal)entry.getValue();
				if(terminal_mac.equals(terminaltmp.getCnt_mac())){
					terminal=terminaltmp;
					boolB=true;
					break;
				}
			}
			if(null==terminal){
				terminal=terminaldao.getTerminalBystr1(new StringBuffer().append(" where cnt_mac='").append(terminal_mac+"'").toString());
			}
		}else{
			 terminal=terminaldao.getTerminalBystr1(new StringBuffer().append(" where cnt_mac='").append(terminal_mac+"'").toString());
		}
		if(boolB){
			Terminal terminal2=terminaldao.getTerminalBystr1(new StringBuffer().append(" where cnt_mac='").append(terminal_mac).append("'").toString());
			terminal.setCnt_kjtime(terminal2.getCnt_kjtime());
			terminal.setCnt_gjtime(terminal2.getCnt_gjtime());
			terminal.setCnt_downtime(terminal2.getCnt_downtime());
			terminal.setCnt_addtime(terminal2.getCnt_addtime());
		}
		request.setAttribute("terminal", terminal);
		
		if("AUDIT".equals(cmd)){
			List allterminal_zu=terminaldao.getAllZu("where zu_type=0");
			request.setAttribute("allterminal_zu", allterminal_zu);
		}
		return mapping.findForward(cmd);
	}
}