/****************************************************

	JConfig Source Code Distribution
	version: 2.2.0      written: 08/23/2002 12:25 PM PDT

	Unless otherwise noted, all contents
	Copyright (c) 1997-2002 Samizdat Productions.
	All Rights Reserved.
	All contents are subject to the terms of the
	JConfig Source Code License Agreement

****************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class com_jconfig_AppUtilsMSVM */

#ifndef _Included_com_jconfig_AppUtilsMSVM
#define _Included_com_jconfig_AppUtilsMSVM

#pragma pack(4)

typedef struct Classcom_jconfig_AppUtilsMSVM {
#undef com_jconfig_AppUtilsMSVM_copyrightString
#define com_jconfig_AppUtilsMSVM_copyrightString 275L
#undef com_jconfig_AppUtilsMSVM_kMaxReturns
#define com_jconfig_AppUtilsMSVM_kMaxReturns 50L
/* Inaccessible static: kStandardBrowsers */
#undef com_jconfig_AppUtilsMSVM_kDateArrayLen
#define com_jconfig_AppUtilsMSVM_kDateArrayLen 6L
#undef com_jconfig_AppUtilsMSVM_kCreationDate
#define com_jconfig_AppUtilsMSVM_kCreationDate 0L
#undef com_jconfig_AppUtilsMSVM_kModDate
#define com_jconfig_AppUtilsMSVM_kModDate 1L
#undef com_jconfig_AppUtilsMSVM_kAccessDate
#define com_jconfig_AppUtilsMSVM_kAccessDate 2L
#undef com_jconfig_AppUtilsMSVM_kCategoryVolume
#define com_jconfig_AppUtilsMSVM_kCategoryVolume 0L
#undef com_jconfig_AppUtilsMSVM_kCategoryDirectory
#define com_jconfig_AppUtilsMSVM_kCategoryDirectory 1L
#undef com_jconfig_AppUtilsMSVM_kCategoryFile
#define com_jconfig_AppUtilsMSVM_kCategoryFile 2L
#undef com_jconfig_AppUtilsMSVM_kCategoryAlias
#define com_jconfig_AppUtilsMSVM_kCategoryAlias 3L
#undef com_jconfig_AppUtilsMSVM_kCategoryUnknown
#define com_jconfig_AppUtilsMSVM_kCategoryUnknown 4L
#undef com_jconfig_AppUtilsMSVM_kMonitorInfoNumInts
#define com_jconfig_AppUtilsMSVM_kMonitorInfoNumInts 20L
#undef com_jconfig_AppUtilsMSVM_kVolumeCapInfoLen
#define com_jconfig_AppUtilsMSVM_kVolumeCapInfoLen 2L
#undef com_jconfig_AppUtilsMSVM_kVolumeCapInfoCapacityOffset
#define com_jconfig_AppUtilsMSVM_kVolumeCapInfoCapacityOffset 0L
#undef com_jconfig_AppUtilsMSVM_kVolumeCapInfoFreeSpaceOffset
#define com_jconfig_AppUtilsMSVM_kVolumeCapInfoFreeSpaceOffset 1L
#undef com_jconfig_AppUtilsMSVM_kGVIStringArrayLen
#define com_jconfig_AppUtilsMSVM_kGVIStringArrayLen 2L
#undef com_jconfig_AppUtilsMSVM_kGVIIntArrayLen
#define com_jconfig_AppUtilsMSVM_kGVIIntArrayLen 3L
#undef com_jconfig_AppUtilsMSVM_kGVIStringLabelOffset
#define com_jconfig_AppUtilsMSVM_kGVIStringLabelOffset 0L
#undef com_jconfig_AppUtilsMSVM_kGVIStringFileSystemNameOffset
#define com_jconfig_AppUtilsMSVM_kGVIStringFileSystemNameOffset 1L
#undef com_jconfig_AppUtilsMSVM_kGVIIntSerialNumberOffset
#define com_jconfig_AppUtilsMSVM_kGVIIntSerialNumberOffset 0L
#undef com_jconfig_AppUtilsMSVM_kGVIIntMaxComponentLengthOffset
#define com_jconfig_AppUtilsMSVM_kGVIIntMaxComponentLengthOffset 1L
#undef com_jconfig_AppUtilsMSVM_kGVIIntFileSystemFlagsOffset
#define com_jconfig_AppUtilsMSVM_kGVIIntFileSystemFlagsOffset 2L
#undef com_jconfig_AppUtilsMSVM_FILE_ATTRIBUTE_READONLY
#define com_jconfig_AppUtilsMSVM_FILE_ATTRIBUTE_READONLY 1L
#undef com_jconfig_AppUtilsMSVM_FILE_ATTRIBUTE_HIDDEN
#define com_jconfig_AppUtilsMSVM_FILE_ATTRIBUTE_HIDDEN 2L
#undef com_jconfig_AppUtilsMSVM_FILE_ATTRIBUTE_SYSTEM
#define com_jconfig_AppUtilsMSVM_FILE_ATTRIBUTE_SYSTEM 4L
#undef com_jconfig_AppUtilsMSVM_FILE_ATTRIBUTE_DIRECTORY
#define com_jconfig_AppUtilsMSVM_FILE_ATTRIBUTE_DIRECTORY 16L
#undef com_jconfig_AppUtilsMSVM_FILE_ATTRIBUTE_ARCHIVE
#define com_jconfig_AppUtilsMSVM_FILE_ATTRIBUTE_ARCHIVE 32L
#undef com_jconfig_AppUtilsMSVM_FILE_ATTRIBUTE_NORMAL
#define com_jconfig_AppUtilsMSVM_FILE_ATTRIBUTE_NORMAL 128L
#undef com_jconfig_AppUtilsMSVM_FILE_ATTRIBUTE_TEMPORARY
#define com_jconfig_AppUtilsMSVM_FILE_ATTRIBUTE_TEMPORARY 256L
#undef com_jconfig_AppUtilsMSVM_kPTDFGotFalse
#define com_jconfig_AppUtilsMSVM_kPTDFGotFalse 0L
#undef com_jconfig_AppUtilsMSVM_kPTDFGotTrue
#define com_jconfig_AppUtilsMSVM_kPTDFGotTrue 1L
#undef com_jconfig_AppUtilsMSVM_kPTDFNotAMatch
#define com_jconfig_AppUtilsMSVM_kPTDFNotAMatch 2L
#undef com_jconfig_AppUtilsMSVM_kErrFindNextFileNoMoreFiles
#define com_jconfig_AppUtilsMSVM_kErrFindNextFileNoMoreFiles 536870953L
#undef com_jconfig_AppUtilsMSVM_kLinkExtension
#define com_jconfig_AppUtilsMSVM_kLinkExtension 92L
/* Inaccessible static: tempDir */
    char PAD;	/* ANSI C requires structures to have a least one member */
} Classcom_jconfig_AppUtilsMSVM;
HandleTo(com_jconfig_AppUtilsMSVM);

#pragma pack()

#ifdef __cplusplus
extern "C" {
#endif
extern long com_jconfig_AppUtilsMSVM_nativeFindClose(struct Hcom_jconfig_AppUtilsMSVM *,long);
struct Hjava_lang_String;
extern long com_jconfig_AppUtilsMSVM_nativeSetVolumeLabel(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,struct Hjava_lang_String *);
extern long com_jconfig_AppUtilsMSVM_nativeGetVolumeInformation(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,HArrayOfString *,HArrayOfInt *);
extern long com_jconfig_AppUtilsMSVM_nativeLaunchURL(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,struct Hjava_lang_String *,long,HArrayOfString *);
extern long com_jconfig_AppUtilsMSVM_nativeGetVolumeCapInfo(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,HArrayOfLong *);
extern long com_jconfig_AppUtilsMSVM_nativeFindAppsByName(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,long,long,HArrayOfInt *,HArrayOfString *);
extern long com_jconfig_AppUtilsMSVM_nativeGetVolumeDate(struct Hcom_jconfig_AppUtilsMSVM *,long,struct Hjava_lang_String *,HArrayOfInt *);
extern long com_jconfig_AppUtilsMSVM_nativeGetFileDate(struct Hcom_jconfig_AppUtilsMSVM *,long,struct Hjava_lang_String *,HArrayOfInt *);
extern long com_jconfig_AppUtilsMSVM_nativeVIPGetFileVersionInfoStart(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *);
extern long com_jconfig_AppUtilsMSVM_nativeGetVolumeIcon(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,long,long,long,long,long,HArrayOfInt *);
extern long com_jconfig_AppUtilsMSVM_nativeGetFileIcon(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,long,long,long,long,long,HArrayOfInt *);
extern long com_jconfig_AppUtilsMSVM_nativeCreateVolumeAlias(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,struct Hjava_lang_String *,long);
extern long com_jconfig_AppUtilsMSVM_nativeGetVolumeFlags(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,HArrayOfInt *);
extern long com_jconfig_AppUtilsMSVM_nativeGetMainMonitorInfo(struct Hcom_jconfig_AppUtilsMSVM *,HArrayOfInt *);
extern long com_jconfig_AppUtilsMSVM_nativeGetExtIcon(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,long,long,long,long,long,HArrayOfInt *);
extern long com_jconfig_AppUtilsMSVM_nativeLaunchApp(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,struct Hjava_lang_String *,struct Hjava_lang_String *,struct Hjava_lang_String *,HArrayOfInt *,long,HArrayOfString *);
extern long com_jconfig_AppUtilsMSVM_nativeGetVolumeReadFlagsMask(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,HArrayOfInt *);
extern long com_jconfig_AppUtilsMSVM_nativeVIPGetFileVersionInfoEnd(struct Hcom_jconfig_AppUtilsMSVM *,long);
extern long com_jconfig_AppUtilsMSVM_nativeGetExecutableType(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,HArrayOfInt *);
extern long com_jconfig_AppUtilsMSVM_nativeFindNextFile(struct Hcom_jconfig_AppUtilsMSVM *,long,HArrayOfInt *,HArrayOfString *);
extern long com_jconfig_AppUtilsMSVM_nativeVIPVerQueryValue(struct Hcom_jconfig_AppUtilsMSVM *,long,struct Hjava_lang_String *,HArrayOfString *);
extern long com_jconfig_AppUtilsMSVM_nativeGetDriveDisplayName(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,HArrayOfString *);
extern long com_jconfig_AppUtilsMSVM_nativeGetFileAttributesMask(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,HArrayOfInt *);
extern long com_jconfig_AppUtilsMSVM_nativeSetFileAttributes(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,long,long);
extern long com_jconfig_AppUtilsMSVM_nativeGetFileAttributesWriteMask(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,HArrayOfInt *);
extern long com_jconfig_AppUtilsMSVM_nativeResolveLinkFile(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,HArrayOfString *,long);
extern long com_jconfig_AppUtilsMSVM_nativeGetFileAttributes(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,HArrayOfInt *);
extern long com_jconfig_AppUtilsMSVM_nativeVerifyNativeAppData(struct Hcom_jconfig_AppUtilsMSVM *,HArrayOfInt *);
extern long com_jconfig_AppUtilsMSVM_nativeCreateFileAlias(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,struct Hjava_lang_String *,long);
extern long com_jconfig_AppUtilsMSVM_nativeQuitApp(struct Hcom_jconfig_AppUtilsMSVM *,HArrayOfInt *,long);
extern long com_jconfig_AppUtilsMSVM_nativeMoveApp(struct Hcom_jconfig_AppUtilsMSVM *,HArrayOfInt *,long,long);
extern long com_jconfig_AppUtilsMSVM_nativeFindVerbs(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,struct Hjava_lang_String *,long,HArrayOfInt *,HArrayOfString *);
extern long com_jconfig_AppUtilsMSVM_nativeGetAllMonitorInfo(struct Hcom_jconfig_AppUtilsMSVM *,HArrayOfInt *,long,HArrayOfInt *);
extern long com_jconfig_AppUtilsMSVM_nativeGetVolumes(struct Hcom_jconfig_AppUtilsMSVM *,long,HArrayOfInt *,HArrayOfString *);
extern long com_jconfig_AppUtilsMSVM_nativeFindFirstFile(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,HArrayOfInt *,HArrayOfInt *,HArrayOfString *);
extern long com_jconfig_AppUtilsMSVM_nativeFindAppsByExtension(struct Hcom_jconfig_AppUtilsMSVM *,struct Hjava_lang_String *,struct Hjava_lang_String *,long,long,HArrayOfInt *,HArrayOfString *);
#ifdef __cplusplus
}
#endif
#endif
