/****************************************************

	JConfig Source Code Distribution
	version: 2.2.0      written: 08/23/2002 12:25 PM PDT

	Unless otherwise noted, all contents
	Copyright (c) 1997-2002 Samizdat Productions.
	All Rights Reserved.
	All contents are subject to the terms of the
	JConfig Source Code License Agreement

****************************************************/

/*  DO NOT EDIT - automatically generated by javah  */
#include <native.h>

/*  Header for class com.jconfig.AppUtilsMSVM  */

#ifndef _Included_com_jconfig_win_AppUtilsMSVM
#define _Included_com_jconfig_win_AppUtilsMSVM

typedef struct Classcom_jconfig_win_AppUtilsMSVM {
#pragma pack(push,4)
	int32_t MSReserved;
#define com_jconfig_win_AppUtilsMSVM_kMaxReturns 50
#define com_jconfig_win_AppUtilsMSVM_kDateArrayLen 6
#define com_jconfig_win_AppUtilsMSVM_kCreationDate 0
#define com_jconfig_win_AppUtilsMSVM_kModDate 1
#define com_jconfig_win_AppUtilsMSVM_kAccessDate 2
#define com_jconfig_win_AppUtilsMSVM_kCategoryVolume 0
#define com_jconfig_win_AppUtilsMSVM_kCategoryDirectory 1
#define com_jconfig_win_AppUtilsMSVM_kCategoryFile 2
#define com_jconfig_win_AppUtilsMSVM_kCategoryAlias 3
#define com_jconfig_win_AppUtilsMSVM_kCategoryUnknown 4
#define com_jconfig_win_AppUtilsMSVM_kMonitorInfoNumInts 20
#define com_jconfig_win_AppUtilsMSVM_kVolumeCapInfoLen 2
#define com_jconfig_win_AppUtilsMSVM_kVolumeCapInfoCapacityOffset 0
#define com_jconfig_win_AppUtilsMSVM_kVolumeCapInfoFreeSpaceOffset 1
#define com_jconfig_win_AppUtilsMSVM_kGVIStringArrayLen 2
#define com_jconfig_win_AppUtilsMSVM_kGVIIntArrayLen 3
#define com_jconfig_win_AppUtilsMSVM_kGVIStringLabelOffset 0
#define com_jconfig_win_AppUtilsMSVM_kGVIStringFileSystemNameOffset 1
#define com_jconfig_win_AppUtilsMSVM_kGVIIntSerialNumberOffset 0
#define com_jconfig_win_AppUtilsMSVM_kGVIIntMaxComponentLengthOffset 1
#define com_jconfig_win_AppUtilsMSVM_kGVIIntFileSystemFlagsOffset 2
#define com_jconfig_win_AppUtilsMSVM_FILE_ATTRIBUTE_READONLY 1
#define com_jconfig_win_AppUtilsMSVM_FILE_ATTRIBUTE_HIDDEN 2
#define com_jconfig_win_AppUtilsMSVM_FILE_ATTRIBUTE_SYSTEM 4
#define com_jconfig_win_AppUtilsMSVM_FILE_ATTRIBUTE_DIRECTORY 16
#define com_jconfig_win_AppUtilsMSVM_FILE_ATTRIBUTE_ARCHIVE 32
#define com_jconfig_win_AppUtilsMSVM_FILE_ATTRIBUTE_NORMAL 128
#define com_jconfig_win_AppUtilsMSVM_FILE_ATTRIBUTE_TEMPORARY 256
#define com_jconfig_win_AppUtilsMSVM_kPTDFGotFalse 0
#define com_jconfig_win_AppUtilsMSVM_kPTDFGotTrue 1
#define com_jconfig_win_AppUtilsMSVM_kPTDFNotAMatch 2
#define com_jconfig_win_AppUtilsMSVM_kErrFindNextFileNoMoreFiles 536870953
#pragma pack(pop)
} Classcom_jconfig_win_AppUtilsMSVM;
#define Hcom_jconfig_win_AppUtilsMSVM Classcom_jconfig_win_AppUtilsMSVM

#ifdef __cplusplus
extern "C" {
#endif
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetShortPathName (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetAllProcessInfo (struct Hcom_jconfig_win_AppUtilsMSVM *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfString *, long, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeVerifyNativeAppData (struct Hcom_jconfig_win_AppUtilsMSVM *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeQuitApp (struct Hcom_jconfig_win_AppUtilsMSVM *, struct HArrayOfInt *, long);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetFileDate (struct Hcom_jconfig_win_AppUtilsMSVM *, long, struct Hjava_lang_String *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeMoveApp (struct Hcom_jconfig_win_AppUtilsMSVM *, struct HArrayOfInt *, long, long);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeFindAppsByName (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, long, long, struct HArrayOfInt *, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeFindAppsByExtension (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct Hjava_lang_String *, long, long, struct HArrayOfInt *, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeFindVerbs (struct Hcom_jconfig_win_AppUtilsMSVM *, struct HArrayOfString *, struct Hjava_lang_String *, long, struct HArrayOfInt *, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeLaunchURL (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct Hjava_lang_String *, long, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeLaunchApp (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct Hjava_lang_String *, struct Hjava_lang_String *, struct Hjava_lang_String *, struct HArrayOfInt *, long, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetVolumeDate (struct Hcom_jconfig_win_AppUtilsMSVM *, long, struct Hjava_lang_String *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeResolveLinkFile (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfString *, long);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetExecutableType (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetFileAttributes (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetFileAttributesMask (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeSetFileAttributes (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, long, long);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetFileAttributesWriteMask (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetAllMonitorInfo (struct Hcom_jconfig_win_AppUtilsMSVM *, struct HArrayOfInt *, long, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetMainMonitorInfo (struct Hcom_jconfig_win_AppUtilsMSVM *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeSetVolumeLabel (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct Hjava_lang_String *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetDriveDisplayName (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetVolumeFlags (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetVolumeReadFlagsMask (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetVolumeCapInfo (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfLong *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetVolumeInformation (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfString *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetVolumes (struct Hcom_jconfig_win_AppUtilsMSVM *, long, struct HArrayOfInt *, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeCreateVolumeAlias (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct Hjava_lang_String *, long);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeCreateFileAlias (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct Hjava_lang_String *, long);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeVIPGetFileVersionInfoStart (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeVIPVerQueryValue (struct Hcom_jconfig_win_AppUtilsMSVM *, long, struct Hjava_lang_String *, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeVIPGetFileVersionInfoEnd (struct Hcom_jconfig_win_AppUtilsMSVM *, long);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetFileIcon (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, long, long, long, long, long, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetExtIcon (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, long, long, long, long, long, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetVolumeIcon (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, long, long, long, long, long, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeFindFirstFile (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeFindNextFile (struct Hcom_jconfig_win_AppUtilsMSVM *, long, struct HArrayOfInt *, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeFindClose (struct Hcom_jconfig_win_AppUtilsMSVM *, long);
#ifdef __cplusplus
}
#endif
#endif
