/*  DO NOT EDIT - automatically generated by msjavah  */
#include <native.h>
#pragma warning(disable:4510)
#pragma warning(disable:4512)
#pragma warning(disable:4610)

struct Classjava_lang_String;
#define Hjava_lang_String Classjava_lang_String
struct Classjava_util_Vector;
#define Hjava_util_Vector Classjava_util_Vector

/*  Header for class com/jconfig/win/AppUtilsMSVM  */

#ifndef _Included_com_jconfig_win_AppUtilsMSVM
#define _Included_com_jconfig_win_AppUtilsMSVM

#define Hcom_jconfig_win_AppUtilsMSVM Classcom_jconfig_win_AppUtilsMSVM
typedef struct Classcom_jconfig_win_AppUtilsMSVM {
#include <pshpack4.h>
	long MSReserved;
#define com_jconfig_win_AppUtilsMSVM_kFindFirstAttrHidden 2
#define com_jconfig_win_AppUtilsMSVM_kFindFirstAttrSystem 4
#define com_jconfig_win_AppUtilsMSVM_kDateBundleArrayLen 18
#define com_jconfig_win_AppUtilsMSVM_DATE_MOD_OFFSET 0
#define com_jconfig_win_AppUtilsMSVM_DATE_CRE_OFFSET 6
#define com_jconfig_win_AppUtilsMSVM_DATE_ACC_OFFSET 12
#define com_jconfig_win_AppUtilsMSVM_kMonitorInfoNumInts 20
#define com_jconfig_win_AppUtilsMSVM_kVolumeCapInfoLen 4
#define com_jconfig_win_AppUtilsMSVM_kVolumeCapInfoCapacityOffset 0
#define com_jconfig_win_AppUtilsMSVM_kVolumeCapInfoFreeSpaceOffset 1
#define com_jconfig_win_AppUtilsMSVM_kVolumeCapInfoCapacityToUserOffset 2
#define com_jconfig_win_AppUtilsMSVM_kVolumeCapInfoFreeSpaceToUserOffset 3
#define com_jconfig_win_AppUtilsMSVM_kResolveLinkFileNoUI 1
#define com_jconfig_win_AppUtilsMSVM_kResolveLinkFileUI 2
#define com_jconfig_win_AppUtilsMSVM_kGVIStringArrayLen 2
#define com_jconfig_win_AppUtilsMSVM_kGVIIntArrayLen 3
#define com_jconfig_win_AppUtilsMSVM_kGVIStringLabelOffset 0
#define com_jconfig_win_AppUtilsMSVM_kGVIStringFileSystemNameOffset 1
#define com_jconfig_win_AppUtilsMSVM_kGVIIntSerialNumberOffset 0
#define com_jconfig_win_AppUtilsMSVM_kGVIIntMaxComponentLengthOffset 1
#define com_jconfig_win_AppUtilsMSVM_kGVIIntFileSystemFlagsOffset 2
#define com_jconfig_win_AppUtilsMSVM_kUnused -1
#include <poppack.h>
} Classcom_jconfig_win_AppUtilsMSVM;

#ifdef __cplusplus
extern "C" {
#endif
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetShortPathName (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetAllProcessInfo (struct Hcom_jconfig_win_AppUtilsMSVM *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfString *, long, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeFindClose (struct Hcom_jconfig_win_AppUtilsMSVM *, long);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeFindNextFile (struct Hcom_jconfig_win_AppUtilsMSVM *, long, struct HArrayOfInt *, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeFindFirstFile (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfInt *, struct HArrayOfInt *, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetVolumeIcon (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, long, long, long, long, long, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetExtIcon (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, long, long, long, long, long, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetFileIcon (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, long, long, long, long, long, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeVIPGetFileVersionInfoEnd (struct Hcom_jconfig_win_AppUtilsMSVM *, long);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeVIPVerQueryValue (struct Hcom_jconfig_win_AppUtilsMSVM *, long, struct Hjava_lang_String *, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeVIPGetFileVersionInfoStart (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeCreateFileAlias (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct Hjava_lang_String *, long);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeCreateVolumeAlias (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct Hjava_lang_String *, long);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetVolumes (struct Hcom_jconfig_win_AppUtilsMSVM *, long, struct HArrayOfInt *, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetVolumeInformation (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfString *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetVolumeCapInfo (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfLong *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetVolumeReadFlagsMask (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetVolumeFlags (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetDriveDisplayName (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeSetVolumeLabel (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct Hjava_lang_String *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetMainMonitorInfo (struct Hcom_jconfig_win_AppUtilsMSVM *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetAllMonitorInfo (struct Hcom_jconfig_win_AppUtilsMSVM *, struct HArrayOfInt *, long, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetFileAttributesWriteMask (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeSetFileAttributes (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, long, long);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetFileAttributesMask (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetFileAttributes (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetExecutableType (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeResolveLinkFile (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct HArrayOfString *, long);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeLaunchURL (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct Hjava_lang_String *, long, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeFindVerbs (struct Hcom_jconfig_win_AppUtilsMSVM *, struct HArrayOfString *, struct Hjava_lang_String *, long, struct HArrayOfInt *, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeFindAppsByExtension (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct Hjava_lang_String *, long, long, struct HArrayOfInt *, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeFindAppsByName (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, long, long, struct HArrayOfInt *, struct HArrayOfString *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeMoveApp (struct Hcom_jconfig_win_AppUtilsMSVM *, struct HArrayOfInt *, long, long);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeQuitApp (struct Hcom_jconfig_win_AppUtilsMSVM *, struct HArrayOfInt *, long);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeVerifyNativeAppData (struct Hcom_jconfig_win_AppUtilsMSVM *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetFileDate (struct Hcom_jconfig_win_AppUtilsMSVM *, long, struct Hjava_lang_String *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeGetVolumeDate (struct Hcom_jconfig_win_AppUtilsMSVM *, long, struct Hjava_lang_String *, struct HArrayOfInt *);
__declspec(dllexport) long __cdecl com_jconfig_win_AppUtilsMSVM_nativeLaunchApp (struct Hcom_jconfig_win_AppUtilsMSVM *, struct Hjava_lang_String *, struct Hjava_lang_String *, struct Hjava_lang_String *, struct Hjava_lang_String *, struct HArrayOfInt *, long, struct HArrayOfString *);
#ifdef __cplusplus
}
#endif

#endif  /* _Included_com_jconfig_win_AppUtilsMSVM */

#pragma warning(default:4510)
#pragma warning(default:4512)
#pragma warning(default:4610)

