/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xct.cms.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-23-2010
 * 
 * XDoclet definition:
 * @struts.form name="auditCntForm"
 */
public class AuditCntForm extends ActionForm {
	/*
	 * Generated fields
	 */
	private String terminal_mac;
	/** cnt_miaoshu property */
	private String cnt_miaoshu;

	/** cnt_kjtime property */
	private String cnt_kjtime;

	/** cnt_gjtime property */
	private String cnt_gjtime;

	/** cnt_downtime property */
	private String cnt_downtime;

	/** terminal_zu property */
	private String terminal_zu;

	/** cnt_name property */
	private String cnt_name;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the cnt_miaoshu.
	 * @return String
	 */
	public String getCnt_miaoshu() {
		return cnt_miaoshu;
	}

	/** 
	 * Set the cnt_miaoshu.
	 * @param cnt_miaoshu The cnt_miaoshu to set
	 */
	public void setCnt_miaoshu(String cnt_miaoshu) {
		this.cnt_miaoshu = cnt_miaoshu;
	}

	/** 
	 * Returns the cnt_kjtime.
	 * @return String
	 */
	public String getCnt_kjtime() {
		return cnt_kjtime;
	}

	/** 
	 * Set the cnt_kjtime.
	 * @param cnt_kjtime The cnt_kjtime to set
	 */
	public void setCnt_kjtime(String cnt_kjtime) {
		this.cnt_kjtime = cnt_kjtime;
	}

	/** 
	 * Returns the cnt_gjtime.
	 * @return String
	 */
	public String getCnt_gjtime() {
		return cnt_gjtime;
	}

	/** 
	 * Set the cnt_gjtime.
	 * @param cnt_gjtime The cnt_gjtime to set
	 */
	public void setCnt_gjtime(String cnt_gjtime) {
		this.cnt_gjtime = cnt_gjtime;
	}

	/** 
	 * Returns the cnt_downtime.
	 * @return String
	 */
	public String getCnt_downtime() {
		return cnt_downtime;
	}

	/** 
	 * Set the cnt_downtime.
	 * @param cnt_downtime The cnt_downtime to set
	 */
	public void setCnt_downtime(String cnt_downtime) {
		this.cnt_downtime = cnt_downtime;
	}

	/** 
	 * Returns the terminal_zu.
	 * @return String
	 */
	public String getTerminal_zu() {
		return terminal_zu;
	}

	/** 
	 * Set the terminal_zu.
	 * @param terminal_zu The terminal_zu to set
	 */
	public void setTerminal_zu(String terminal_zu) {
		this.terminal_zu = terminal_zu;
	}

	/** 
	 * Returns the cnt_name.
	 * @return String
	 */
	public String getCnt_name() {
		return cnt_name;
	}

	/** 
	 * Set the cnt_name.
	 * @param cnt_name The cnt_name to set
	 */
	public void setCnt_name(String cnt_name) {
		this.cnt_name = cnt_name;
	}

	
	public String getTerminal_mac() {
		return terminal_mac;
	}

	public void setTerminal_mac(String terminal_mac) {
		this.terminal_mac = terminal_mac;
	}
}