/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xct.cms.xy.action;
import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xct.cms.dao.LogsDAO;
import com.xct.cms.dao.ProgramAppDAO;
import com.xct.cms.dao.ProgramDAO;
import com.xct.cms.db.DBConnection;
import com.xct.cms.domin.CntResponse;
import com.xct.cms.domin.ProgramApp;
import com.xct.cms.servlet.FirstStartServlet;
import com.xct.cms.utils.DESPlusUtil;
import com.xct.cms.utils.Util;
import com.xct.cms.utils.UtilDAO;
import com.xct.cms.xy.dao.ManagerProjectDao;

public class DownloadResultAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		//成都鼎润 linux下用
		try {
			request.setCharacterEncoding("UTF-8");
		} catch (UnsupportedEncodingException e1) {
			e1.printStackTrace();
		}
	
		//接收客户端发送过来的状态 
		// xu0009  命令返回过来的url：http://192.168.10.7:80/rq/downloadresult?cmd=xu0009&cmdStatus=xu0009_OK&programurl=20110413151826!543&cmdResult=
		String cnt_ip=request.getRemoteAddr();
		String cnt_cmd=request.getParameter("cmd")==null?"":request.getParameter("cmd");
		String cnt_cmdstatus=request.getParameter("cmdStatus")==null?"_":request.getParameter("cmdStatus").trim();
		String cnt_cmdResult=request.getParameter("cmdResult")==null?"":request.getParameter("cmdResult").trim();//节目字串或其他
		String cnt_programurlandid=request.getParameter("programurl")==null?"":request.getParameter("programurl").trim();
//		System.out.println("cnt_programurlandid-------------->"+cnt_programurlandid);//programurl=20110413151826!563$$$563#
		
//		System.out.println("cnt_cmd-----1----->"+cnt_cmd);
//		System.out.println("cmdStatus-----1----->"+cnt_cmdstatus);
//		System.out.println("cnt_cmdResult-----1----->"+cnt_cmdResult);
//		try {
//			System.out.println("cnt_cmdResult-----5----->"+new String(cnt_cmdResult.getBytes(),"GBK"));
//		} catch (UnsupportedEncodingException e) {
//			e.printStackTrace();
//		}
		
		Connection conn = new DBConnection().getConection();
		
		List<ProgramApp> programapplist=new ArrayList<ProgramApp>();
		
		String[] sttmp=null;
		if(!"xu0028".equals(cnt_cmd)&&null!=cnt_programurlandid&&!"".equals(cnt_programurlandid)){
			sttmp=cnt_programurlandid.split("A");
			String tempstring=sttmp[1];
			String []idstmp=((tempstring.indexOf("!")!=-1)?tempstring.split("!"):new String[]{tempstring});
			ProgramAppDAO programappdao=new ProgramAppDAO();
			for(int i=0,n=idstmp.length;i<n;i++){
				if(!idstmp[i].equals("")&&null!=idstmp[i])
				  programapplist.add(programappdao.getProgramAppByStr(conn,"where id="+idstmp[i]));
			}
		}
		
		LogsDAO logsdao= new LogsDAO();
		
		if("xu0009".equals(cnt_cmd)){
				String cnt_programurl=sttmp[0].split("!")[0];
				String cnt_programid=sttmp[0].split("!")[1];
				
				ManagerProjectDao managerprojectdao=new ManagerProjectDao();
				////////////////*************更新终端下载节目状态
				
				Map<String,CntResponse> map=FirstStartServlet.downloadProgramStatus;
				CntResponse cntrp= new CntResponse();
				cntrp.setCnt_ip(cnt_ip);
				cntrp.setCnt_cmd(cnt_cmd);
				cntrp.setCnt_cmdstatus(cnt_cmdstatus);
				cntrp.setCnt_cmdresult(cnt_cmdResult);
				cntrp.setCnt_programurl(cnt_programurl);
				map.put(cnt_ip,cntrp);
				FirstStartServlet.downloadProgramStatus=map;
				
				if(cnt_cmdstatus.equals("xu0009_OK")){
					 ProgramApp programapp;
					 logsdao.addlogs1(conn,"system", "<span>终端"+cnt_ip+"下载节目成功</span>", 1);
					 for(int i=0,n=programapplist.size();i<n;i++){
						 programapp=programapplist.get(i);
						 managerprojectdao.updateProjectIsSend(conn,2,1,programapp.getProgram_jmurl(),cnt_ip);//  把值改成 2 表示 下载成功 ,0 表示今天和今天以后的未发送的节目，
					 }
					 String sql=" update xct_JMApp set program_sendok_terminal=program_sendok_terminal+'#"+cnt_ip+"' where id="+cnt_programid;
					 new ProgramAppDAO().UpdateSendState(conn, sql);
					 
				}else{
					 logsdao.addlogs1(conn,"system", "<span>终端"+cnt_ip+"下载节目失败。(失败原因："+cntrp.getCnt_cmdresultZh().replace("<img src='/images/error.gif'  height='16px'>", "").replace("'","")+")</span>", 1);
					 managerprojectdao.updateProjectIsSend(conn,3,1,cnt_programurl,cnt_ip);//  把值改成 3 表示 下载失败
				}
			}else if("xu0005".equals(cnt_cmd)){
				if("xu0005_OK".equals(cnt_cmdstatus)){
					logsdao.addlogs1(conn,"system", "<span>终端"+cnt_ip+"重启成功</span>", 1);
				}else{
					logsdao.addlogs1(conn,"system", "<span>终端"+cnt_ip+"重启失败</span>", 1);
				}
			}else if("xu0024".equals(cnt_cmd)){
				if("xu0024_OK".equals(cnt_cmdstatus)){
					logsdao.addlogs1(conn,"system", "<span>终端"+cnt_ip+"接受文字通知成功</span>", 1);
				}else{
					logsdao.addlogs1(conn,"system", "<span>终端"+cnt_ip+"接受文字通知失败</span>", 1);
				}
			}else if("xu0018".equals(cnt_cmd)){
				if("xu0018_OK".equals(cnt_cmdstatus)){
					logsdao.addlogs1(conn,"system", "<span>终端"+cnt_ip+"软件升级成功</span>", 1);
				}else{
					logsdao.addlogs1(conn,"system", "<span>终端"+cnt_ip+"软件升级失败</span>", 1);
				}
			}else if("xu0028".equals(cnt_cmd)){
				UtilDAO utildao= new  UtilDAO();
				String nowtime =utildao.getNowtime("yyyy-MM-dd HH:mm:ss");
				Map map= utildao.getMap();
				map.put("cnt_ip", cnt_ip);
				map.put("cnt_cmd", cnt_cmd);
				map.put("cnt_cmdstatus", cnt_cmdstatus);
				map.put("cnt_cmdresult", cnt_cmdResult.trim());
				map.put("cnt_programurl", cnt_programurlandid);
				map.put("cnt_sendtime", nowtime);
				utildao.saveinfo(conn,map, "xct_cnt_response");
			}
		    if(null!=conn){
		    	try {
					conn.close();
				} catch (SQLException e) {
					e.printStackTrace();
				}
		    }
		return null;
	}
}