/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xct.cms.xy.action;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xct.cms.xy.dao.GetAllClinetDao;
import com.xct.cms.xy.domain.ClientIpAddress;

/** 
 * MyEclipse Struts
 * Creation date: 09-01-2010
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class SelectProjectAction extends Action {
	
	String result;
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String info="";
		try {
			info = new String(request.getParameter("info").getBytes("ISO-8859-1"),"gbk");
		} catch (UnsupportedEncodingException e1) {
			e1.printStackTrace();
		}
		PrintWriter out=null;
		try {
			out = response.getWriter();
		} catch (IOException e) {
			e.printStackTrace();
		}
		int counter = 0;    
		GetAllClinetDao getallclinetdao=new GetAllClinetDao();
		Map<String,ClientIpAddress>ipmap=getallclinetdao.getClient(info);
		for(Map.Entry<String, ClientIpAddress> map:ipmap.entrySet()){
			 if (counter > 0) {
	              out.print("|");
	         }
	         counter++;    
			 result=map.getKey();
			 out.print(result);//将结果写入响应体
		}
		return null;
	}
}