/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xct.cms.xy.action;

import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.xct.cms.xy.dao.ManagerProjectDao;
import com.xct.cms.xy.domain.ClientProjectBean;

public class ViewClientProjectAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
        int pages=10; //每页 显示10条
        int pagecount=1; //传过来的页码
        int allpages=0;  //总页数
        int allpagestemp=0;
        ManagerProjectDao managerprojectdao=new ManagerProjectDao();
        String  playclient=request.getParameter("playclient");
        String  starttime=request.getParameter("starttime");
        String  endtime=request.getParameter("endtime");
        String  pagecounttemp=request.getParameter("pagecount");
        String  jmid=request.getParameter("jmid");
        
	    pagecount=(null==pagecounttemp?1:Integer.parseInt(pagecounttemp));		
		if(null!=jmid&&!"".equals(jmid)){
			//删除选中的节目
				///////System.out.println("jmid= "+jmid);
				managerprojectdao.deleteClientProject(Integer.parseInt(jmid));
	    }
		allpagestemp=managerprojectdao.getClientProect1(starttime, endtime,playclient,"");
		if(allpagestemp%pages==0)//得到总页数
				allpages=allpagestemp/pages;
			else
				allpages=allpagestemp/pages+1;
		List<ClientProjectBean> clientprojectbeanlist =	managerprojectdao.getClientProect1(pages, pagecount, starttime,endtime,playclient,"");
		request.setAttribute("allpages", allpages);//显示所有页面总数
		request.setAttribute("pagecount",pagecount);// 显示当前在第几页
		request.setAttribute("clientprojectbeanlist",clientprojectbeanlist);//显示查出的数据
		request.setAttribute("searchstr", playclient);//播放器名称
		request.setAttribute("onedate", starttime);//开始时间
		 
	   return mapping.findForward("success");
	}
}